version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  pgbackups:
    container_name: postgres_backup_container
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - /var/opt/pgbackups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_POST=${POSTGRES_HOST:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-gamedaim}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

  server:
    container_name: server_container
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./packages/server/.env
    ports:
      - "8000:8000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  web:
    container_name: web_container
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    depends_on:
      - server
    env_file:
      - ./packages/web/.env
    ports:
      - "3000:3000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres:
