interface EnvProps {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any
}

const env: EnvProps = {
  NODE_ENV: process.env.NODE_ENV || "development",
  API: process.env.NEXT_PUBLIC_API || "http://localhost:8000",
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN || "localhost",
  ADSENSE_CLIENT_ID: process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID,
  SITE_TITLE: process.env.NEXT_PUBLIC_SITE_TITLE,
  DESCRIPTION: process.env.NEXT_PUBLIC_DESCRIPTION,
  SITE_COLOR: process.env.NEXT_PUBLIC_SITE_COLOR,
  SITE_LANGUAGE: process.env.NEXT_PUBLIC_SITE_LANGUAGE,
  GA_MEASUREMTNT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  TWITTER_USERNAME: process.env.NEXT_PUBLIC_TWITTER_USERNAME,
  FACEBOOK_USERNAME: process.env.NEXT_PUBLIC_FACEBOOK_USERNAME,
  INSTAGRAM_USERNAME: process.env.NEXT_PUBLIC_INSTAGRAM_USERNAME,
  LINKEDIN_USERNAME: process.env.NEXT_PUBLIC_LINKEDIN_USERNAME,
  PINTEREST_USERNAME: process.env.NEXT_PUBLIC_PINTEREST_USERNAME,
  FACEBOOK_ID: process.env.NEXT_PUBLIC_FACEBOOK_ID,
  LOGO_URL: process.env.NEXT_PUBLIC_LOGO_URL,
  LOGO_WIDTH: process.env.NEXT_PUBLIC_LOGO_WIDTH,
  LOGO_HEIGHT: process.env.NEXT_PUBLIC_LOGO_HEIGHT,
  LOGO_OG_URL: process.env.NEXT_PUBLIC_LOGO_OG_URL,
  LOGO_OG_WIDTH: process.env.NEXT_PUBLIC_LOGO_OG_WIDTH,
  LOGO_OG_HEIGHT: process.env.NEXT_PUBLIC_LOGO_OG_HEIGHT,
}

export default env
